### ISSUE TITLE
Select gets slightly bigger height on firefox 59

### ISSUE THREAD

**Issue by kootoopas** [Ajusa/lit#18]
🔥💔
<img width="942" alt="screen shot 2018-02-15 at 8 14 22 pm" src="https://user-images.githubusercontent.com/601001/36273347-e0d6fb6e-128c-11e8-8a65-72b8b2e58663.png">

**Comment by kootoopas** [comment]
os is macos high sierra btw

**Comment by Ajusa** [comment]
Hm... I will have to test that. Thanks for bringing it up!

**Comment by Ajusa** [comment]
Sorry, I haven't gotten around to testing this yet. I've been busy with school work. Hopefully I'll have it fixed and released this week

**Comment by kootoopas** [comment]
@Ajusa I think that it's not worth it to have selects with consistent appearance across browsers, since it adds significant size and may require a container element too. Excerpt from [relevant article](https://clicknathan.com/web-design/styling-select-elements-crossbrowser/):

```css
select {
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
}

.select-container {position:relative; display: inline;}
.select-container:after {content:""; width:0; height:0; position:absolute; pointer-events: none;}
.select-container:after {
    top: .3em;
    right: .75em;
}

select::-ms-expand {
    display: none;
}
```
