### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by kaihendry** [ajusa/lit#23]
For people who `prefers-color-scheme: dark` please :laughing:

**Comment by ajusa** [comment]
Sorry for the late reply! This is something I don't think I would consider adding to lit at this time, since the goal is to remain extremely lean. If you want to make an existing lit project be dark, here is a quick example:
```css
* {
    background: #2E3440 !important;
    color: white;
}
```
and it should work. If enough people support this, I'll consider adding it to the core but for now I would just use that snippet.
